"""
Deepfake Audio - Vocoder Training Script
----------------------------------------
This script orchestrates the training of the Vocoder (WaveRNN) model.
It utilizes the Ground Truth Aligned (GTA) spectrograms generated by
`vocoder_preprocess.py` to train the model to synthesize high-fidelity waveforms.

WaveRNN is a recurrent neural network that generates raw audio samples autoregressively,
conditioned on the mel spectrogram frames.

Authors:
    - Amey Thakur (https://github.com/Amey-Thakur)
    - Mega Satish (https://github.com/msatmod)

Repository:
    - https://github.com/Amey-Thakur/DEEPFAKE-AUDIO

Release Date:
    - February 06, 2021

License:
    - MIT License

Description:
    Training involves:
    1.  **Data Loading**: Ingesting GTA spectrograms and corresponding target audio.
    2.  **Model Optimization**: Minimizing the discrepancy between generated and actual audio samples.
    3.  **Checkpointing**: Saving model states for inference or resumption.
"""

import argparse
from pathlib import Path
from typing import Optional

# Standard Library Imports
from utils.argutils import print_args

# Internal Modules
from vocoder.train import train


def main() -> None:
    """
    Main execution routine for vocoder training.
    """
    
    parser = argparse.ArgumentParser(
        description="Trains the WaveRNN Vocoder using GTA mel spectrograms.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    
    # -------------------------------------------------------------------------
    # Positional Arguments
    # -------------------------------------------------------------------------
    parser.add_argument("run_id", type=str, help= \
        "Unique Name/ID for this training run. Resumes from checkpoint if it exists.")
        
    parser.add_argument("datasets_root", type=str, help= \
        "Path to the root directory containing the SV2TTS structure. "
        "Used to infer default input/output paths for synthesizer/vocoder data.")
    
    # -------------------------------------------------------------------------
    # Optional Arguments
    # -------------------------------------------------------------------------
    parser.add_argument("--syn_dir", type=str, default=argparse.SUPPRESS, help= \
        "Direct path to synthesizer directory (wavs/mels). "
        "Defaults to <datasets_root>/SV2TTS/synthesizer/.")
        
    parser.add_argument("--voc_dir", type=str, default=argparse.SUPPRESS, help= \
        "Direct path to vocoder directory (GTA mels). "
        "Defaults to <datasets_root>/SV2TTS/vocoder/. Unused if --ground_truth is set.")
        
    parser.add_argument("-m", "--models_dir", type=str, default="vocoder/saved_models/", help=\
        "Directory for saving model checkpoints and logs.")
        
    parser.add_argument("-g", "--ground_truth", action="store_true", help= \
        "Train on ground truth mels (from synthesizer) instead of GTA mels. "
        "Generally leads to lower quality inference but faster training setup.")
        
    parser.add_argument("-s", "--save_every", type=int, default=1000, help= \
        "Step interval for saving model checkpoints.")
        
    parser.add_argument("-b", "--backup_every", type=int, default=25000, help= \
        "Step interval for keeping long-term backups.")
        
    parser.add_argument("-f", "--force_restart", action="store_true", help= \
        "Force training to start from scratch, ignoring existing checkpoints.")
        
    args = parser.parse_args()

    # -------------------------------------------------------------------------
    # Configuration
    # -------------------------------------------------------------------------
    # Resolve paths
    if not hasattr(args, "syn_dir"):
        args.syn_dir = Path(args.datasets_root, "SV2TTS", "synthesizer")
    args.syn_dir = Path(args.syn_dir)
    
    if not hasattr(args, "voc_dir"):
        args.voc_dir = Path(args.datasets_root, "SV2TTS", "vocoder")
    args.voc_dir = Path(args.voc_dir)
    
    # Clean up namespace
    del args.datasets_root
    
    # Setup model directory
    args.models_dir = Path(args.models_dir)
    args.models_dir.mkdir(exist_ok=True, parents=True) # Added parents=True for robustness

    # -------------------------------------------------------------------------
    # Execution
    # -------------------------------------------------------------------------
    print_args(args, parser)
    train(**vars(args))


if __name__ == "__main__":
    main()
    